University.Teacher/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using University.Shared.Dtos.AuthDtos;
using University.Shared.Dtos.MainDtos;
using University.Shared.Interfaces.AuthInterfaces;
using University.Shared.Utility;

namespace University.Teacher.Controllers;

public class AuthController : Controller
{
    private readonly IAuthService _authService;
    private readonly ITokenProvider _tokenProvider;
    public AuthController(IAuthService authService, ITokenProvider tokenProvider)
    {
        _authService = authService;
        _tokenProvider = tokenProvider;
    }

    [HttpGet]
    public IActionResult Login()
    {
        LoginRequestDto loginRequestDto = new();
        return View(loginRequestDto);
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginRequestDto loginRequestDto)
    {
        ResponseDto login = await _authService.LoginAsync(loginRequestDto);

        if (login != null && login.IsSuccess)
        {
            string result = Convert.ToString(login.Result);

            LoginResponseDto loginResponseDto = JsonConvert.DeserializeObject<LoginResponseDto>(result);

            await SignInAsync(loginResponseDto);

            _tokenProvider.SetToken(loginResponseDto.Token);

            return RedirectToAction("Index", "Home");
        }
        else
        {
            TempData["error"] = login.Message;
            return View(loginRequestDto);
        }
    }

    [HttpGet]
    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Register(RegistrationRequestDto registrationRequestDto)
    {
        ResponseDto register = await _authService.RegisterAsync(registrationRequestDto);

        if (register != null && register.IsSuccess)
        {
            registrationRequestDto.RoleName = SD.RoleAdmin;

            var assignRole = await _authService.AssignRoleAsync(registrationRequestDto);

            if (assignRole != null && assignRole.IsSuccess)
            {
                TempData["success"] = "Registration was successful";

                return RedirectToAction(nameof(Login));
            }
        }
        else
        {
            TempData["error"] = register.Message;
        }

        return View(registrationRequestDto);
    }

    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync();
        _tokenProvider.ClearToken();

        return RedirectToAction("Index", "Home");
    }

    private async Task SignInAsync(LoginResponseDto loginResponseDto)
    {
        var handler = new JwtSecurityTokenHandler();

        var jwt = handler.ReadJwtToken(loginResponseDto.Token);

        var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

        identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Email).Value));
        identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Sub).Value));
        identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Name).Value));
        identity.AddClaim(new Claim(JwtRegisteredClaimNames.FamilyName, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.FamilyName).Value));
        identity.AddClaim(new Claim(JwtRegisteredClaimNames.GivenName, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.GivenName).Value));
        identity.AddClaim(new Claim(JwtRegisteredClaimNames.UniqueName, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.UniqueName).Value));
        identity.AddClaim(new Claim(ClaimTypes.Name, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Email).Value));
        identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(x => x.Type == "role").Value));

        var principal = new ClaimsPrincipal(identity);

        await HttpContext.SignInAsync("TeacherCookie", principal);
    }
}

University.Teacher/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using University.Shared.Dtos.TeacherDtos;
using University.Shared.Interfaces.TeacherInterfaces;
using University.Shared.Utility;

namespace University.Teacher.Controllers;

[Authorize(Roles = SD.RoleTeacher)]
public class TeacherController : Controller
{
    private readonly ITeacherInterface _teacherService;
    public TeacherController(ITeacherInterface teacherService)
    {
        _teacherService = teacherService;
    }

    public async Task<IActionResult> Index()
    {
        var userId = User.FindFirstValue(JwtRegisteredClaimNames.Sub);
        var responseDto = await _teacherService.GetTeacherProfile(userId);
        
        if (responseDto.Result == null)
        {
            return View();
        }

        var teacherDto = JsonConvert.DeserializeObject<TeacherDto>(responseDto.Result.ToString());

        return View(teacherDto);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateProfile(TeacherDto teacherDto)
    {
        if (ModelState.IsValid)
        {
            teacherDto.UserId = Guid.Parse(User.FindFirstValue(JwtRegisteredClaimNames.Sub));
            await _teacherService.CreateTeacherProfile(teacherDto);
            return RedirectToAction("Index");
        }
        return View("Index", teacherDto);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> UpdateProfile(TeacherDto teacherDto)
    {
        if (ModelState.IsValid)
        {
            await _teacherService.UpdateTeacherProfile(teacherDto);
            return RedirectToAction("Index");
        }
        return View("Index", teacherDto);
    }
}

University.Teacher/Controllers/TeacherCoursesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using University.Shared.Dtos.CourseDtos;
using University.Shared.Dtos.TeacherDtos;
using University.Shared.Interfaces.CourseInterfaces;
using University.Shared.Interfaces.TeacherInterfaces;

namespace University.Teacher.Controllers;

[Authorize(Roles = "TEACHER")]
public class TeacherCoursesController : Controller
{
    private readonly ITeacherCoursesInterface _teacherCoursesService;
    private readonly ICourseService _courseService;
    private readonly IFacultyService _facultyService;

    public TeacherCoursesController(
        ITeacherCoursesInterface teacherCoursesService,
        ICourseService courseService,
        IFacultyService facultyService
        )
    {
        _teacherCoursesService = teacherCoursesService;
        _courseService = courseService;
        _facultyService = facultyService;
    }

    public async Task<IActionResult> Index()
    {
        var responseDto = await _teacherCoursesService.GetTeacherCourses();

        var courses = new List<TeacherCoursesDto>();

        if (responseDto.Result != null)
            courses = JsonConvert.DeserializeObject<List<TeacherCoursesDto>>(responseDto.Result.ToString());

        return View(courses);
    }

    [HttpGet]
    public async Task<JsonResult> GetCourses()
    {
        var responseDto = await _courseService.GetAllCourses();
        var courses = JsonConvert.DeserializeObject<List<CourseDto>>(responseDto.Result.ToString());
        return Json(courses);
    }

    [HttpGet]
    public async Task<JsonResult> GetFaculties()
    {
        var responseDto = await _facultyService.GetAllFaculties();

        var faculties = new List<FacultyDto>();

        if(responseDto.Result != null)
            faculties = JsonConvert.DeserializeObject<List<FacultyDto>>(responseDto.Result.ToString());
        
        return Json(faculties);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddCourse(TeacherCoursesDto teacherCoursesDto)
    {
        if (ModelState.IsValid)
        {
            teacherCoursesDto.UserId = Guid.Parse(User.FindFirstValue(JwtRegisteredClaimNames.Sub));
            var response = await _teacherCoursesService.AddTeacherCourses(teacherCoursesDto);
            if (response.IsSuccess)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(string.Empty, response.Message);
        }
        return View("Index", new List<TeacherCoursesDto>());
    }
}

University.Teacher/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - University.Teacher</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/University.Teacher.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark border-bottom mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">University.Portal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Teacher" asp-action="Index">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="TeacherCourses" asp-action="Index">Courses</a>
                            </li>
                        }

                    </ul>

                    <ul class="navbar-nav">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <p class="nav-link text-white">@User.Identity.Name</p>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - University.Teacher - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>