University.Portal/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using University.Shared.Dtos.AuthDtos;
using University.Shared.Dtos.MainDtos;
using University.Shared.Interfaces.AuthInterfaces;
using University.Shared.Utility;

namespace University.Portal.Controllers;

public class AuthController : Controller
{
    private readonly IAuthService _authService;
    private readonly ITokenProvider _tokenProvider;
    public AuthController(IAuthService authService, ITokenProvider tokenProvider)
    {
        _authService = authService;
        _tokenProvider = tokenProvider;
    }

    [HttpGet]
    public IActionResult Login()
    {
        LoginRequestDto loginRequestDto = new();
        return View(loginRequestDto);
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginRequestDto loginRequestDto)
    {
        ResponseDto login = await _authService.LoginAsync(loginRequestDto);

        if (login != null && login.IsSuccess)
        {
            string result = Convert.ToString(login.Result);

            LoginResponseDto loginResponseDto = JsonConvert.DeserializeObject<LoginResponseDto>(result);

            await SignInAsync(loginResponseDto);

            _tokenProvider.SetToken(loginResponseDto.Token);

            return RedirectToAction("Index", "Home");
        }
        else
        {
            TempData["error"] = login.Message;
            return View(loginRequestDto);
        }
    }

    [HttpGet]
    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Register(RegistrationRequestDto registrationRequestDto)
    {
        ResponseDto register = await _authService.RegisterAsync(registrationRequestDto);

        if (register != null && register.IsSuccess)
        {
            registrationRequestDto.RoleName = SD.RoleAdmin;

            var assignRole = await _authService.AssignRoleAsync(registrationRequestDto);

            if (assignRole != null && assignRole.IsSuccess)
            {
                TempData["success"] = "Registration was successful";

                return RedirectToAction(nameof(Login));
            }
        }
        else
        {
            TempData["error"] = register.Message;
        }

        return View(registrationRequestDto);
    }

    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync();
        _tokenProvider.ClearToken();

        return RedirectToAction("Index", "Home");
    }

    [Authorize(Roles = SD.RoleAdmin)]
    public async Task<IActionResult> Users()
    {
        var userDtos = new List<UserDto>();
        ResponseDto responseDto = await _authService.GetUsers();

        if (responseDto.Result != null)
        {
            string resultString = Convert.ToString(responseDto.Result);
            userDtos = JsonConvert.DeserializeObject<List<UserDto>>(resultString);
        }

        return View(userDtos);
    }

    public IActionResult CreateUser()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateUser(RegistrationRequestDto registrationRequestDto)
    {
        ResponseDto register = await _authService.RegisterAsync(registrationRequestDto);

        if (register != null && register.IsSuccess)
        {
            var assignRole = await _authService.AssignRoleAsync(registrationRequestDto);

            if (assignRole != null && assignRole.IsSuccess)
            {
                TempData["success"] = "New user was added";

                return RedirectToAction(nameof(Users));
            }
        }
        else
        {
            TempData["error"] = register.Message;
        }

        return View(registrationRequestDto);
    }

    public async Task<IActionResult> UpdateUser(string userId)
    {
        ResponseDto responseDto = await _authService.GetUserById(userId);

        if (responseDto.Result != null)
        {
            string resultString = Convert.ToString(responseDto.Result);
            UserDto userDto = JsonConvert.DeserializeObject<UserDto>(resultString);

            return View(userDto);
        }

        return NotFound();
    }

    [HttpPost]
    public async Task<IActionResult> UpdateUser(UserDto userDto)
    {
        ResponseDto responseDto = await _authService.UpdateUserAsync(userDto);

        if (responseDto != null && responseDto.IsSuccess)
        {
            TempData["success"] = "User Was updated";
            return RedirectToAction(nameof(Users));
        }

        TempData["error"] = responseDto.Message;
        return View(userDto);
    }

    [HttpPost]
    public async Task<IActionResult> DeleteUser(string userId)
    {
        ResponseDto responseDto = await _authService.DeleteUser(userId);

        if (responseDto != null && responseDto.IsSuccess)
            TempData["success"] = "User Was deleted";
        else
            TempData["error"] = responseDto.Message;

        return RedirectToAction(nameof(Users));
    }

    private async Task SignInAsync(LoginResponseDto loginResponseDto)
    {

        var handler = new JwtSecurityTokenHandler();

        var jwt = handler.ReadJwtToken(loginResponseDto.Token);

        var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

        identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Email).Value));
        identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Sub).Value));
        identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Name).Value));
        identity.AddClaim(new Claim(JwtRegisteredClaimNames.FamilyName, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.FamilyName).Value));
        identity.AddClaim(new Claim(JwtRegisteredClaimNames.GivenName, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.GivenName).Value));
        identity.AddClaim(new Claim(JwtRegisteredClaimNames.UniqueName, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.UniqueName).Value));
        identity.AddClaim(new Claim(ClaimTypes.Name, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Email).Value));
        identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(x => x.Type == "role").Value));

        var principal = new ClaimsPrincipal(identity);

        await HttpContext.SignInAsync("PortalCookie", principal);
    }
}

University.Portal/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using University.Shared.Dtos.CourseDtos;
using University.Shared.Dtos.MainDtos;
using University.Shared.Interfaces.CourseInterfaces;

namespace University.Portal.Controllers;

public class CourseController : Controller
{
    private readonly ICourseService _courseService;
    private readonly IFacultyService _facultyService;
    public CourseController(ICourseService courseService, IFacultyService facultyService)
    {
        _courseService = courseService;
        _facultyService = facultyService;
    }

    public async Task<IActionResult> Index()
    {
        ResponseDto responseDto = await _courseService.GetAllCourses();

        if (responseDto == null || !responseDto.IsSuccess)
        {
            TempData["error"] = "Something went wrong";
            return View(new List<CourseDto>());
        }

        string resultString = Convert.ToString(responseDto.Result);
        IEnumerable<CourseDto> courses = JsonConvert.DeserializeObject<IEnumerable<CourseDto>>(resultString);

        return View(courses);
    }

    public async Task<IActionResult> AddCourse()
    {
        ResponseDto responseDto = await _facultyService.GetAllFaculties();
        string resultString = Convert.ToString(responseDto.Result);
        ViewBag.Faculties = JsonConvert.DeserializeObject<IEnumerable<FacultyDto>>(resultString);

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> AddCourse(CourseDto courseDto)
    {
        if (!ModelState.IsValid)
        {
            return View(courseDto);
        }

        ResponseDto responseDto = await _courseService.Add(courseDto);

        if (responseDto == null || !responseDto.IsSuccess)
        {
            TempData["error"] = "Something went wrong";
            return View(courseDto);
        }

        TempData["success"] = "Course added successfully";
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> UpdateCourse(int courseId)
    {
        ResponseDto responseDto = await _courseService.GetCourseById(courseId);

        string responseString = Convert.ToString(responseDto.Result);

        CourseDto courseDto = JsonConvert.DeserializeObject<CourseDto>(responseString);

        // Get faculties
        ResponseDto faculties = await _facultyService.GetAllFaculties();
        string facultiesString = Convert.ToString(faculties.Result);
        ViewBag.Faculties = JsonConvert.DeserializeObject<IEnumerable<FacultyDto>>(facultiesString);

        return View(courseDto);
    }

    [HttpPost]
    public async Task<IActionResult> UpdateCourse(CourseDto courseDto)
    {
        if (!ModelState.IsValid)
        {
            return View(courseDto);
        }

        ResponseDto responseDto = await _courseService.Update(courseDto);

        if (responseDto == null || !responseDto.IsSuccess)
        {
            TempData["error"] = "Something went wrong";
            return View(courseDto);
        }

        TempData["success"] = "Course updated successfully";
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<IActionResult> DeleteCourse(int courseId)
    {
        ResponseDto responseDto = await _courseService.Delete(courseId);

        if (responseDto == null || !responseDto.IsSuccess)
        {
            TempData["error"] = "Something went wrong";
        }
        else
        {
            TempData["success"] = "Course deleted successfully";
        }
        return RedirectToAction(nameof(Index));
    }

}

University.Portal/Controllers/FacultyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using University.Shared.Dtos.CourseDtos;
using University.Shared.Dtos.MainDtos;
using University.Shared.Interfaces.CourseInterfaces;

namespace University.Portal.Controllers;

[Authorize]
public class FacultyController : Controller
{
    private readonly IFacultyService _facultyService;
    public FacultyController(IFacultyService facultyService)
    {
        _facultyService = facultyService;
    }

    public async Task<IActionResult> Index()
    {
        ResponseDto responseDto = await _facultyService.GetAllFaculties();

        if (responseDto == null || !responseDto.IsSuccess)
        {
            TempData["error"] = "Something went wrong";
            return View(new List<FacultyDto>());
        }

        string resultString = Convert.ToString(responseDto.Result);
        IEnumerable<FacultyDto> faculties = JsonConvert.DeserializeObject<IEnumerable<FacultyDto>>(resultString);

        return View(faculties);
    }

    public IActionResult AddFaculty()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> AddFaculty(FacultyDto facultyDto)
    {
        if (!ModelState.IsValid)
        {
            return View(facultyDto);
        }

        ResponseDto responseDto = await _facultyService.Add(facultyDto);

        if (responseDto == null || !responseDto.IsSuccess)
        {
            TempData["error"] = "Something went wrong";
            return View(facultyDto);
        }

        TempData["success"] = "Faculty added successfully";
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> UpdateFaculty(int facultyId)
    {
        ResponseDto responseDto = await _facultyService.GetFacultyById(facultyId);

        string resultString = Convert.ToString(responseDto.Result);

        FacultyDto facultyDto = JsonConvert.DeserializeObject<FacultyDto>(resultString);

        return View(facultyDto);
    }

    [HttpPost]
    public async Task<IActionResult> UpdateFaculty(FacultyDto facultyDto)
    {
        if (!ModelState.IsValid)
        {
            return View(facultyDto);
        }

        ResponseDto responseDto = await _facultyService.Update(facultyDto);

        if (responseDto == null || !responseDto.IsSuccess)
        {
            TempData["error"] = "Something went wrong";
            return View(facultyDto);
        }

        TempData["success"] = "Faculty added successfully";
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<IActionResult> DeleteFaculty(int facultyId)
    {
        ResponseDto responseDto = await _facultyService.Delete(facultyId);

        if (responseDto == null || !responseDto.IsSuccess)
        {
            TempData["error"] = "Something went wrong";
        }
        else
        {
            TempData["success"] = "Faculty deleted successfully";
        }
        return RedirectToAction(nameof(Index));
    }
}

University.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - University.Portal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/University.Portal.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css" integrity="sha512-oe8OpYjBaDWPt2VmSFR+qYOdnTjeV9QPLJUeqZyprDEQvQLJ9C5PCFclxwNuvb/GQgQngdCXzKSFltuHD3eCxA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark border-bottom mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">University.Portal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Faculty" asp-action="Index">Faculties</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Auth" asp-action="Users">User management</a>
                            </li>
                        }

                    </ul>

                    <ul class="navbar-nav">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <p class="nav-link text-white">@User.Identity.Name</p>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notifications.cshtml" />

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - University.Portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

University.Portal/Views/Shared/_Notifications.cshtml
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}

@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}